- alias: Xiaomi_switch1_both

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_both_158d0001641685
        click_type: both

  action: 
    - service: light.toggle
      entity_id: group.bathroomlights
