- alias: Xiaomi_switch1_left

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0001641685
        click_type: single

  action:
    - service: python_script.light
      data_template:
        entity_id: group.bathroomlights
        action: toggle
