- alias: Xiaomi_switch1_right

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d0001641685
        click_type: single
       
  action: 
    - service: python_script.light
      data_template:
        entity_id: group.bathroomlights
        action: dim_toggle
