
- alias: Xiaomi_button1_double_off

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001101bc1
        click_type: double

  condition:
    - condition: state
      entity_id: light.livingroom_rgb
      state: 'on'

  action: 
    - service: switch.turn_off
      entity_id: switch.nyan_lights
    - service: light.turn_off
      entity_id: light.livingroom_rgb


- alias: Xiaomi_button1_double_on

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001101bc1
        click_type: double

  condition:
    - condition: state
      entity_id: light.livingroom_rgb
      state: 'off'

  action: 
    - service: light.turn_on
      entity_id: light.livingroom_rgb
      data:
        brightness: 255
        rgb_color: [255,255,255]
