
- alias: Xiaomi_button1_long

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001101bc1
        click_type: long_click_press
        
  action: 
    - service: switch.toggle
      entity_id: switch.nyan_lights
