- action:
  - service: switch.turn_off
  alias: New Automation
  condition: []
  id: '1524472532434'
  trigger:
  - above: '78'
    below: '73'
    entity_id: sensor.temperature_158d00018734a1
    platform: numeric_state
