- action:
  - alias: ''
    data: {}
    service: light.turn_off
  alias: New Automation
  condition: []
  id: '1509948709583'
  trigger:
  - entity_id: light.hallway
    from: 'off'
    platform: state
    to: 'on'
