- alias: Xiaomi_switch2_both

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_both_158d000164164b
        click_type: both

  action:
    - service: python_script.light
      data_template:
        entity_id: group.hallwaylights
        action: toggle
