- alias: Xiaomi_cube1_free_fall

  trigger: 
    - platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000101bc14
        action_type: free_fall

  action:
    - service: python_script.light     
      data_template:
        entity_id: light.office
        action: toggle
