
- alias: Xiaomi_button6_double

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00019df118
        click_type: double
        
  action:
    - service: python_script.light
      data_template:
        entity_id: group.bedroomlights
        action: dim_toggle
