
- alias: Xiaomi_button6_long

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00019df118
        click_type: long_click_press
        
  action: 
    - service: scene.turn_on
      entity_id: scene.turn_off_all_lights
    - service: scene.turn_on
      entity_id: scene.turn_off_all_devices
