
- alias: Xiaomi_button6_long

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00019df118
        click_type: long_click_press
        
  action: 
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.moving_lights
    - service: scene.turn_on
      entity_id: scene.turn_off_all_devices
    - service: switch.turn_off
      entity_id: switch.sonoff1
    - delay: 00:00:02
    - service: switch.turn_on
      entity_id: switch.sonoff1
    - service: scene.turn_on
      entity_id: scene.turn_off_all_lights
    - service: cover.close_cover
      entity_id: cover.curtain_158d000288203a
