- alias: Xiaomi_button6_single

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00019df118
        click_type: single

  action:
    - service: python_script.light     
      data_template:
        entity_id: group.bedroomlights
        action: toggle
