
- alias: Xiaomi_button4_double

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d000186eafb
        click_type: double
        
  action:
    - service: python_script.light
      data_template:
        entity_id: group.officelights
        action: dim_toggle
