
- alias: Xiaomi_button4_long

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d000186eafb
        click_type: long_click_press
        
  action:
    - service: python_script.light
      data_template:
        entity_id: light.printer
        action: toggle
