
- alias: Xiaomi_button4_single

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000186eafb
        click_type: single

  action:
    - service: python_script.light     
      data_template:
        entity_id: light.office
        action: toggle
