
- alias: Xiaomi_button7_double

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00019dbca6
        click_type: double
        
  action:
    - service: python_script.light
      data_template:
        entity_id: group.diningroomlights
        action: dim_toggle
        max: 200
