
- alias: Xiaomi_button3_double

  trigger: 
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00013f878a
        click_type: double
        
  action:
    - service: python_script.light
      data_template:
        entity_id: group.livingroomlamps
        action: dim_toggle
