
- alias: Xiaomi_button5_single_off

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00019df1ef
        click_type: single

  condition:
    - condition: state
      entity_id: switch.switch1
      state: 'on'
        
  action: 
    - service: switch.turn_off
      entity_id: switch.switch1


- alias: Xiaomi_button5_single_on

  trigger: 
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00019df1ef
        click_type: single
       
  condition:
    - condition: state
      entity_id: switch.switch1
      state: 'off'

  action: 
    - service: switch.turn_on
      entity_id: switch.switch1

