
- alias: Livingroom play

  trigger: 
    - platform: state
      entity_id: media_player.living_room_tv
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room_tv
      to: 'idle'

  condition:
    - condition: state
      entity_id: group.livingroomlamps
      state: 'on'
        
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_media_play

- alias: Livingroom stop

  trigger: 
    - platform: state
      entity_id: media_player.living_room_tv
      to: 'off'
       
  condition:
    - condition: state
      entity_id: group.livingroomlamps
      state: 'on'

  action:
    service: scene.turn_on
    entity_id: scene.livingroom_media_stop
