
- alias: Livingroom play

  trigger: 
    - platform: state
      entity_id: media_player.living_room_tv
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room_tv
      to: 'idle'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.livingroomlamps
        state: 'on'
      - condition: state
        entity_id: input_boolean.moving_lights
        state: 'off'
        
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_media_play

- alias: Livingroom stop

  trigger: 
    - platform: state
      entity_id: media_player.living_room_tv
      to: 'off'
       
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.livingroomlamps
        state: 'on'
      - condition: state
        entity_id: input_boolean.moving_lights
        state: 'off'

  action:
    service: scene.turn_on
    entity_id: scene.livingroom_media_stop
