
- alias: Lights - Turn off Lights at Sunrise

  trigger: 
    - platform: sun
      event: 'sunrise'
      offset: '-00:15:00'

  action: 
    - service: scene.turn_on
      entity_id: scene.sunrise
