
- alias: 'Turn a few lights on when the sun gets dim'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.5
  action:
    service: scene.turn_on
    entity_id: scene.prepresunset

- alias: 'Turn a few lights on when the sun gets dimmer'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.75
  action:
    service: scene.turn_on
    entity_id: scene.presunset

- alias: 'Turn more lights on as the sun gets dark'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.0
  action:
    service: scene.turn_on
    entity_id: scene.sunset
