
- alias: 'Turn a few lights on when the sun gets dim1'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.5
  action:
    service: scene.turn_on
    entity_id: scene.presunset1

- alias: 'Turn a few lights on when the sun gets dim2'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.1
  action:
    service: scene.turn_on
    entity_id: scene.presunset2

- alias: 'Turn a few lights and close the curtains on when the sun gets dim3'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.8
  action:
    service: scene.turn_on
    entity_id: scene.presunset3

- alias: 'Turn a few lights on when the sun gets dim4'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.4
  action:
    service: scene.turn_on
    entity_id: scene.presunset4

- alias: 'Turn more lights on as the sun gets dark'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.0
  action:
    service: scene.turn_on
    entity_id: scene.sunset
